//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icaCamionesASPv4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DESACDCEntities : DbContext
    {
        public DESACDCEntities()
            : base("name=DESACDCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<pr_OrdenTransporte> pr_OrdenTransporte { get; set; }
        public virtual DbSet<rl_TransportistaFlota> rl_TransportistaFlota { get; set; }
        public virtual DbSet<tb_Auxiliar> tb_Auxiliar { get; set; }
        public virtual DbSet<tb_Ciudad> tb_Ciudad { get; set; }
        public virtual DbSet<tb_Comuna> tb_Comuna { get; set; }
        public virtual DbSet<tb_Flota> tb_Flota { get; set; }
        public virtual DbSet<tb_Producto> tb_Producto { get; set; }
        public virtual DbSet<tb_Provincia> tb_Provincia { get; set; }
        public virtual DbSet<tb_Region> tb_Region { get; set; }
        public virtual DbSet<tb_Ruta> tb_Ruta { get; set; }
        public virtual DbSet<tb_RutaTipo> tb_RutaTipo { get; set; }
        public virtual DbSet<tb_TipoFlota> tb_TipoFlota { get; set; }
        public virtual DbSet<tb_Transportista> tb_Transportista { get; set; }
        public virtual DbSet<se_Roles> se_Roles { get; set; }
        public virtual DbSet<tb_Conductor> tb_Conductor { get; set; }
        public virtual DbSet<tb_Usuarios> tb_Usuarios { get; set; }
    
        public virtual ObjectResult<Ps_se_Roles_byUsu_Result> Ps_se_Roles_byUsu(Nullable<int> cOD_USU)
        {
            var cOD_USUParameter = cOD_USU.HasValue ?
                new ObjectParameter("COD_USU", cOD_USU) :
                new ObjectParameter("COD_USU", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ps_se_Roles_byUsu_Result>("Ps_se_Roles_byUsu", cOD_USUParameter);
        }
    
        public virtual int Ps_se_Roles_Create(Nullable<int> cOD_USU, string nOM_ROL, string dES_ROL)
        {
            var cOD_USUParameter = cOD_USU.HasValue ?
                new ObjectParameter("COD_USU", cOD_USU) :
                new ObjectParameter("COD_USU", typeof(int));
    
            var nOM_ROLParameter = nOM_ROL != null ?
                new ObjectParameter("NOM_ROL", nOM_ROL) :
                new ObjectParameter("NOM_ROL", typeof(string));
    
            var dES_ROLParameter = dES_ROL != null ?
                new ObjectParameter("DES_ROL", dES_ROL) :
                new ObjectParameter("DES_ROL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ps_se_Roles_Create", cOD_USUParameter, nOM_ROLParameter, dES_ROLParameter);
        }
    
        public virtual int Ps_se_Roles_Delete(Nullable<int> cOD_USU)
        {
            var cOD_USUParameter = cOD_USU.HasValue ?
                new ObjectParameter("COD_USU", cOD_USU) :
                new ObjectParameter("COD_USU", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ps_se_Roles_Delete", cOD_USUParameter);
        }
    
        public virtual int Ps_se_Roles_Update(Nullable<int> cOD_USU, string nOM_ROL, string dES_ROL)
        {
            var cOD_USUParameter = cOD_USU.HasValue ?
                new ObjectParameter("COD_USU", cOD_USU) :
                new ObjectParameter("COD_USU", typeof(int));
    
            var nOM_ROLParameter = nOM_ROL != null ?
                new ObjectParameter("NOM_ROL", nOM_ROL) :
                new ObjectParameter("NOM_ROL", typeof(string));
    
            var dES_ROLParameter = dES_ROL != null ?
                new ObjectParameter("DES_ROL", dES_ROL) :
                new ObjectParameter("DES_ROL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ps_se_Roles_Update", cOD_USUParameter, nOM_ROLParameter, dES_ROLParameter);
        }
    }
}
