//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icaCamionesASPv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pr_OrdenTransporte
    {
        public int idOrderTransporte { get; set; }
        public int idCliente { get; set; }
        public int IdProducto { get; set; }
        public int IdRutaTipo { get; set; }
        public string Unidad { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public System.DateTime FechaTermino { get; set; }
        public Nullable<double> Tarifa { get; set; }
        public string usuario { get; set; }
        public string host { get; set; }
    }
}
