//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icaCamionesASPv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class se_Roles
    {
        public int COD_ROL { get; set; }
        public Nullable<int> COD_USU { get; set; }
        public string NOM_ROL { get; set; }
        public string DES_ROL { get; set; }
    }
}
