//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icaCamionesASPv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Auxiliar
    {
        public int idAuxiliar { get; set; }
        public string RUT { get; set; }
        public string Nombre { get; set; }
        public string Giro { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> idComuna { get; set; }
        public string Telefono { get; set; }
        public string email { get; set; }
        public string ClaCliente { get; set; }
        public string ClaProveedor { get; set; }
        public string usuario { get; set; }
        public string host { get; set; }
    }
}
