//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icaCamionesASPv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Flota
    {
        public int idFlota { get; set; }
        public string Patente { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> Ayear { get; set; }
        public string Clasificacion { get; set; }
        public Nullable<int> idTipoCamion { get; set; }
        public string usuario { get; set; }
        public string host { get; set; }
        public string habilitado { get; set; }
    }
}
