//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icaCamionesASPv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_RutaTipo
    {
        public int idRutaTipo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdRutaO { get; set; }
        public Nullable<int> IdRutaD { get; set; }
        public string Referencia { get; set; }
        public string usuario { get; set; }
        public string host { get; set; }
    }
}
