//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace icaCamionesASPv4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Usuarios
    {
        public int COD_USU { get; set; }
        public string NOM_USU { get; set; }
        public string NIC_USU { get; set; }
        public string PER_USU { get; set; }
        public string PWD_USU { get; set; }
        public string EMAIL_USU { get; set; }
        public string TELF_USU { get; set; }
        public string RUT_USU { get; set; }
    }
}
